basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'


from rest_framework import renderers

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r"^updateinfo/(?P<pk>[\w-]+)/$",views.UpdateUserInfo.as_view(),name="updateinfo"),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^profilepage',views.List_product_for_profile.as_view(),name='profilepage'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

django_private_chat/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views
app_name = 'django_private_chat'

from rest_framework import renderers


urlpatterns = [
    url(
        regex=r'^dialogs/(?P<username>[\w.@+-]+)$',
        view=views.DialogListView.as_view(),
        name='dialogs_detail'
    ),
    url(
        regex=r'^dialogs/$',
        view=views.DialogListView.as_view(),
        name='dialogs'
    ),
]

learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django_private_chat import urls as django_private_chat_urls



urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^', include('django_private_chat.urls')),
    url(r"^admin/", admin.site.urls),
    #url(r'^password_reset/$', auth_views.LoginView.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.LoginView.password_reset_done, name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^',include('basic_app.urls')),
    url(r'^',include('productapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productapp/urls.py
from django.conf.urls import url
from . import views
from .views import ProductViewSet
from rest_framework.urlpatterns import format_suffix_patterns
app_name = 'productapp'

from rest_framework import renderers

urlpatterns = [
    url(r"^$", views.ProductList.as_view(), name="all_products"),
    url(r"^updateProduct/(?P<pk>[\w-]+)/$",views.ProductUpdateView.as_view(),name="updateProduct"),
    url(r"^in/(?P<slug>[-\w]+)/$",views.SingleColgProduct.as_view(),name="singlecolg"),
    url(r"^newproduct/$",views.CreateProduct.as_view(), name="create"),
    url(r"^in/(?P<slug>[-\w]+)/in/(?P<pk>\d+)/$",views.SingleProduct.as_view(),name="single"),
    url(r'^autocomplete/$',views.AutoCompleteView.as_view(), name='autocomplete'),
    ]

urlpatterns = format_suffix_patterns(urlpatterns)

productapp/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from basic_app.models import IntitutionModel,UserProfileInfo
from django.utils.text import slugify

# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

# This is our category Table.
class ProductCategoryModel(models.Model):
    typeOfProduct = models.CharField(primary_key = True,max_length = 150)

    def __str__(self):
        return self.typeOfProduct

# this is out product model and related attributes to it.
class ProductsModel(models.Model):
    user = models.ForeignKey(User,related_name = 'products',on_delete = True)
    categoryid = models.ForeignKey(ProductCategoryModel, related_name = 'products',on_delete = True)
    Institution = models.ForeignKey(IntitutionModel,related_name = 'products',blank=False,on_delete = True)
    Institutionslug=models.SlugField(allow_unicode=True)
    #  i am not making title unique at here because i will make unique at
    # late point where sellerid,categoryid and title together will unique.
    title = models.CharField(max_length = 512)
    prize = models.DecimalField(max_digits=8, decimal_places=2)
    Description = models.TextField()
    productImage1 = models.ImageField(upload_to='photos/',blank = False)
    productImage2 = models.ImageField(upload_to = 'photos/',blank=True)
    productImage3 = models.ImageField(upload_to = 'photos/',blank=True)
    productImage4 = models.ImageField(upload_to = 'photos/',blank=True)
    # This flag is used to watch either the product is sold or not.
    soldFlag = models.BooleanField(default=False)
    #this field is added to get time when the product is uploaded.
    createdTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.Institutionslug = slugify(self.Institution)
        # self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("productapp:singlecolg", kwargs={"slug": self.Institutionslug})


    class Meta:
        ordering = ["-createdTime"]
        unique_together = ["user", "categoryid",'title']

productapp/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.generic import UpdateView
from productapp.models import ProductsModel,ProductCategoryModel
from basic_app.models import UserProfileInfo,IntitutionModel
from django.core.exceptions import ObjectDoesNotExist
from braces.views import SelectRelatedMixin
from django.http import HttpResponse
import json
from django.utils.text import slugify
import operator
from django.db.models import Q
from functools import reduce

#rest framework imports
from rest_framework.response import Response
from rest_framework import status
from productapp.models import ProductsModel
from productapp.serializer import ProductSerializer
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework import permissions

from rest_framework.decorators import detail_route
from rest_framework.response import Response
from rest_framework import viewsets
from productapp.permissions import IsOwnerOrReadOnly

class ProductViewSet(viewsets.ModelViewSet):
    queryset = ProductsModel.objects.all()
    serializer_class = ProductSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly)

class SingleProduct(generic.DetailView):
    model = ProductsModel

class SingleColgProduct(generic.ListView):
    model = ProductsModel

    def get_queryset(self):
        result  = super(SingleColgProduct, self).get_queryset()
        result  = result .filter(Institutionslug__exact=self.kwargs.get("slug"))
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(Description__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(categoryid__exact=q) for q in query_list))
            )
        return result

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['category_list'] = ProductCategoryModel.objects.all()
        return data

#this will generate a product list.
class ProductList(generic.ListView):
    model = ProductsModel

    def get_queryset(self):
        if self.request.user.is_authenticated() :
            qs = super(ProductList, self).get_queryset()
            return qs.filter(Institution__exact=UserProfileInfo.objects.get(user=self.request.user).NameOfInstitute)
        else:
            return ProductsModel.objects.all()

#this class is for creation of product.
class CreateProduct(LoginRequiredMixin, generic.CreateView):
    fields = ("categoryid","title",'prize','Description','productImage1','productImage2','productImage3','productImage4')
    model = ProductsModel

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.Institution = UserProfileInfo.objects.get(user=self.request.user).NameOfInstitute
        self.object.save()
        return super().form_valid(form)

#for the updation of product view.
class ProductUpdateView(UpdateView):
    model = ProductsModel
    fields = ("categoryid","title",'prize','Description','productImage1','productImage2','productImage3','productImage4')
    template_name = 'productapp/updateProduct.html'

    def get_success_url(self):
        return reverse('index')

#auto completion of Institution name.
class AutoCompleteView(generic.FormView):
    def get(self,request,*args,**kwargs):
        data = request.GET
        Institutename = data.get('term', '')
        print(Institutename)
        users = IntitutionModel.objects.filter(name__icontains=Institutename)
        if Institutename :
            users = IntitutionModel.objects.filter(name__icontains=Institutename)
            print('hello')
            results = []
            for user in users:
                user_json = {}
                user_json['id'] = user.pk
                user_json['label'] = user.name
                user_json['value'] = user.name
                results.append(user_json)
            data = json.dumps(results)
        else:
            data = 'fail'
        mimetype = 'application/json'
        return HttpResponse(data, mimetype)

productapp/templates/productapp/product_base.html
{% extends "basic_app\base.html" %}
{% block body_block %}
    
<div class="container">

  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

productapp/templates/productapp/productsmodel_detail.html
{% extends "productapp\product_base.html" %}

    {% block group_content %}

    <div class="" style="border:2px solid black;">


      {% if productsmodel.user.username != user.username %}
      <a href="{% url 'django_private_chat:dialogs_detail' productsmodel.user.username %}" class="btn btn-primary">Chat with {{ productsmodel.user.username }}</a>
      {% else %}
      <a href="{% url 'productapp:updateProduct' pk=productsmodel.pk %}"><button type="button" name="button" class="btn btn-simple">Update</button></a>
      {% endif %}
      <h2>{{ productsmodel.title }}</xh2>
      <h3>Category : {{productsmodel.categoryid}}</h3>
      <h3>Description : {{productsmodel.Description}}</h3>
      <h3>Price : {{productsmodel.prize}}</h3>
      <img src="{{ productsmodel.productImage1.url }}" alt="noImage" class="img-responsive img-rounded"  height="200" width="200">
      {% if productsmodel.productImage2 %}
          <img src="{{ productsmodel.productImage2.url }}" alt=" " class="img-responsive img-rounded"  height="200" width="200">
      {% endif %}
      {% if productsmodel.productImage3 %}
          <img src="{{ productsmodel.productImage3.url }}" alt=" " class="img-responsive img-rounded"  height="200" width="200">
      {% endif %}
      {% if productsmodel.productImage4 %}
          <img src="{{ productsmodel.productImage4.url }}" alt=" " class="img-responsive img-rounded"  height="200" width="200">
      {% endif %}
    </div>
    {% endblock %}

productapp/templates/productapp/productsmodel_form.html
{% extends "productapp\product_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form enctype="multipart/form-data" method="POST" action="{% url 'productapp:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

productapp/templates/productapp/productsmodel_list.html
{% extends "productapp\product_base.html" %}

    {% block group_content %}

    <form id="searchform" action="" method="get" accept-charset="utf-8">
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
<button class="searchbutton" type="submit">
<i class="fa fa-search">Search</i>
</button>
</form>
     <form class="" action="" method="get" accept-charset="utf-8" >
       <select class="" name="q" type="text">
         {% for obj in category_list %}
           <option value="{{obj.pk}}">{{obj.typeOfProduct}}</option>
         {% endfor %}
       </select>
       <button class="searchbutton" type="submit">
       <i class="fa fa-search">Search</i>
       </button>
     </form>


       {# Here i am going to filter all the products according to their Institution #}

        {% if object_list %}

        {% for ob in object_list %}
          <div class="" style="border:2px solid black;">
                  <a href="{% url 'productapp:single' slug=ob.Institutionslug pk=ob.pk %}"><h2>Title : {{ob.title}}</h2></a>
                  <h3>Category : {{ob.categoryid}}</h3>
                  <h3>Description : {{ob.Description}}</h3>
                  <h3>Price : {{ob.prize}}</h3>
                  <img src="{{ ob.productImage1.url }}" alt="noImage" class="img-responsive img-rounded"  height="200" width="200">

          </div>
          <br>
        {% endfor %}

        {% else %}

        <h1>Please Post add for your college Here By Logging in.</h1>

        {% endif %}


    {% endblock %}

productapp/templates/productapp/profilepage.html
{% extends "basic_app\base.html" %}

{% block body_block %}

<form id="searchform" action="" method="get" accept-charset="utf-8">
<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
<button class="searchbutton" type="submit">
<i class="fa fa-search">Search</i>
</button>
</form>

 <form class="" action="" method="get" accept-charset="utf-8" >
   <select class="" name="pt" type="text">
    <option value="cycle">cyclel</option>
    <option value="notes">Notes</option>
   </select>
   <button class="searchbutton" type="submit">
   <i class="fa fa-search">Search</i>
   </button>
 </form>


   {# Here i am going to filter all the products according to their Institution #}

    {% if object_list %}

    {% for ob in object_list %}
      <div class="" style="border:2px solid black;">
              <a href="{% url 'productapp:single' slug=ob.Institutionslug pk=ob.pk %}"><h2>Title : {{ob.title}}</h2></a>
              <h3>Category : {{ob.categoryid}}</h3>
              <h3>Description : {{ob.Description}}</h3>
              <h3>Price : {{ob.prize}}</h3>
              <img src="{{ ob.productImage1.url }}" alt="noImage" class="img-responsive img-rounded"  height="200" width="200">
              <a href="{% url 'productapp:profilepageupdate' pk=ob.pk %}"><button type="button" name="button">Update</button></a>
      </div>
      <br>
    {% endfor %}

    {% else %}

    <h1>Please Post add for your college Here By Logging in.</h1>

    {% endif %}
    {% endblock %}

productapp/templates/productapp/updateProduct.html
{% extends "basic_app\base.html" %}
{% load bootstrap3 %}
{% block body_block %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Update" />
</form>
{% endblock %}