basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'


from rest_framework import renderers

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r"^updateinfo/(?P<pk>[\w-]+)/$",views.UpdateUserInfo.as_view(),name="updateinfo"),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^profilepage',views.List_product_for_profile.as_view(),name='profilepage'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django_private_chat import urls as django_private_chat_urls



urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^', include('django_private_chat.urls')),
    url(r"^admin/", admin.site.urls),
    #url(r'^password_reset/$', auth_views.LoginView.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.LoginView.password_reset_done, name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^',include('basic_app.urls')),
    url(r'^',include('productapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productapp/urls.py
from django.conf.urls import url
from . import views
from .views import ProductViewSet
from rest_framework.urlpatterns import format_suffix_patterns
app_name = 'productapp'

from rest_framework import renderers

urlpatterns = [
    url(r"^$", views.ProductList.as_view(), name="all_products"),
    url(r"^updateProduct/(?P<pk>[\w-]+)/$",views.ProductUpdateView.as_view(),name="updateProduct"),
    url(r"^in/(?P<slug>[-\w]+)/$",views.SingleColgProduct.as_view(),name="singlecolg"),
    url(r"^newproduct/$",views.CreateProduct.as_view(), name="create"),
    url(r"^in/(?P<slug>[-\w]+)/in/(?P<pk>\d+)/$",views.SingleProduct.as_view(),name="single"),
    url(r'^autocomplete/$',views.AutoCompleteView.as_view(), name='autocomplete'),
    ]

urlpatterns = format_suffix_patterns(urlpatterns)

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

class IntitutionModel(models.Model):
    name = models.CharField(primary_key=True,max_length=512)
    slug = models.SlugField(allow_unicode=True, unique=True)
     #it will be show on object field.

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("productapp:all_products", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]


# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete = True)
    NameOfInstitute = models.ForeignKey(IntitutionModel,on_delete = True)
    slugInst = models.SlugField(allow_unicode=True)


    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

    def save(self, *args, **kwargs):
        self.slugInst = slugify(self.NameOfInstitute)
        super().save(*args, **kwargs)

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo,IntitutionModel
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):

    class Meta():
        model = User
        fields = ('username','email','password1',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError('Email addresses must be unique.')
        return email


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('NameOfInstitute',)

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm



# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from basic_app.models import IntitutionModel,UserProfileInfo
from django.views import generic
from productapp.models import ProductsModel


#this is the list of product which comes under profile of person.

class UpdateUserInfo(generic.UpdateView):
    model = User
    fields = ('first_name','last_name')
    template_name = 'UpdateUserInfo.html'

    def get_success_url(self):
        return reverse('index')

class List_product_for_profile(generic.ListView):
    model = ProductsModel
    template_name = 'profilepage.html'

    def get_queryset(self):
        qs = super(List_product_for_profile,self).get_queryset()
        return qs.filter(user__exact=self.request.user)

    def get_success_url(self):
        return reverse('profilepage')

# Create your views here.
def index(request):
    item = IntitutionModel.objects.all()
    nameofInst = 'hello'
    if request.user.is_authenticated :
        nameofInst = UserProfileInfo.objects.get(user=request.user).slugInst
    return render(request,'basic_app/index.html',{'items':item,'instName':nameofInst})

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            print('hello world')
            user = user_form.save(commit=False)
            user.is_active = False
            user.save()

            # # Hash the password
            # user.set_password(user.password)
            #
            # # Update with Hashed password
            # user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            # if 'profile_pic' in request.FILES:
            #     print('found it')
            #     # If yes, then grab it from the POST form reply
            #     profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True
            current_site = get_current_site(request)
            message = render_to_string('acc_active_email.html', {
                'user':user,
                'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your blog account.'
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("<h1>Please Confirm Your Email First!.</h1>")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("<h1>Invalid login details supplied.</h1>")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <meta charset="utf-8">
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet" type="text/css" media="all">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css" media="all">
      <link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
     <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
     <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
     </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
     <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
     <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
     {% block css %}{% endblock %}
     {% block Edit_head_for_registration %}

     {% endblock %}
  </head>
  <body>


    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
    

          {# Django Home Link / Admin Link / Register Link#}
          <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">CD</a></li>
          </ul>
          {# <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>#}

            {# <li><a class="navbar-link" href="{% url 'special' %}">Special</a></li>#}

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'dialogs' %}" class="btn btn-simple" >Messages</a></li>
            <li><a href="{% url 'basic_app:profilepage' %}" class="btn btn-simple" >Profile Page</a></li>
            <li><a href="{% url 'productapp:create' %}" class="btn btn-simple">Post Add</a></li>
            <li><a href="{% url 'password_change' %}" class="btn btn-simple">Reset Password</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>

          {% else %}
          <ul class="nav navbar-nav navbar-right">
            {# <li><a href="{% url 'productapp:create' %}" class="btn btn-simple">Post Add</a></li>#}
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          </ul>
          {% endif %}
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    {% block body_block %}
    {% endblock %}
    </div>


    <script type="text/javascript">
         $(function() {
         $("#new-user").autocomplete({
         source: "/productapp/autocomplete/",
         minLength: 2,
         });
         });
 </script>
 <script src="{% static "js/jquery.min.js" %}" type="text/javascript"></script>
 <script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
 <script src="{% static "js/handlebars-v1.3.0.js" %}" type="text/javascript"></script>

  {% block extra_js %}{% endblock %}

  </body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block Edit_head_for_registration %}
<script type="text/javascript">
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>

<script type="text/javascript">
function newpage() {
window.location.replace('{% url 'productapp:singlecolg' slug=instName %}');
}

</script>

{% endblock %}

{% block body_block %}

<!-- jumbotron -->
<div class="container">
  <div class="jumbotron">
    <h1> Tutorial</h1> 
    <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing
    responsive, mobile-first projects on the web.</p> 
  </div>
  
</div>

<div class="container">
  <div >
    {% if user.is_authenticated %}
         <script>newpage();</script>
    {% else %}
        <h1>Search Your College Here</h1>
        <select name="item_id" class="js-example-basic-single" onchange="location = this.value;">
            <option value="hello">hello</option>
        {% for entry in items %}
          <option value="{% url 'productapp:singlecolg' slug=entry.slug %}">{{ entry.name }}</option>
        {% endfor %}
        </select>
    {% endif %}

    {# This piece of code is added to implement autosearch #}
</form>

    {# <input name="user_name"class="form-control "id="new-user"> #}
    {# <input type="search" name="" value="search"> #}
  </div>
</div>

{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password"></label>
          <input type="password" name="password">
          <a href="{% url 'password_reset' %}">Forgot Password</a>
          <input type="submit" name="" value="Login">
        </form>

    </div>
  </div>
{% endblock %}

templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block Edit_head_for_registration %}
<script>
$(document).ready(function() {
    $('#id_NameOfInstitute').select2();
});
              </script>
{% endblock %}


{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{  user_form.as_p }}
          {{  profile_form.as_p}}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>

  </div>

{% endblock %}